server: 
    port: 8090
spring:
    application:
        name: mscv-gataway
    cloud:
        gateway:
            routes:

            #Gateway
            - id: mcsv-oauth
              uri: http://localhost:9100
              predicates:
              - Path= /api/v1/security/**
              filters:
              - StripPrefix=3
            
            #Products
            - id: mcsv-products
              uri: http://localhost:8001
              predicates:
              - Path= /api/v1/products/**
              filters:
              - StripPrefix=3
              - name: Cookie
                args:
                    message: hi
                    name: user
                    value: diego

